version: '3.8'

services:
  # HTTP Web Server
  web-server:
    image: nginx:alpine
    container_name: esp-test-webserver
    ports:
      - "8080:80"
    volumes:
      - ./docker/web-content:/usr/share/nginx/html:ro
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      esp-test-network:
        ipv4_address: 172.20.0.10
    restart: unless-stopped

  # FTP Server
  ftp-server:
    image: stilliard/pure-ftpd:hardened
    container_name: esp-test-ftpserver
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: "172.20.0.11"
      FTP_USER_NAME: "testuser"
      FTP_USER_PASS: "testpass"
      FTP_USER_HOME: "/home/testuser"
    volumes:
      - ./docker/ftp-data:/home/testuser:rw
    networks:
      esp-test-network:
        ipv4_address: 172.20.0.11
    restart: unless-stopped

  # SSH Server
  ssh-server:
    image: linuxserver/openssh-server:latest
    container_name: esp-test-sshserver
    ports:
      - "2222:2222"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: UTC
      PUBLIC_KEY_FILE: /config/authorized_keys
      SUDO_ACCESS: false
      PASSWORD_ACCESS: true
      USER_PASSWORD: testpass
      USER_NAME: testuser
    volumes:
      - ./docker/ssh-config:/config:rw
    networks:
      esp-test-network:
        ipv4_address: 172.20.0.12
    restart: unless-stopped

  # Print Server (CUPS)
  print-server:
    image: olbat/cupsd:latest
    container_name: esp-test-printserver
    ports:
      - "631:631"
    environment:
      CUPSADMIN: admin
      CUPSPASSWORD: secret
    volumes:
      - ./docker/cups-config:/etc/cups:rw
    networks:
      esp-test-network:
        ipv4_address: 172.20.0.13
    restart: unless-stopped
    privileged: true

  # mDNS Reflector/Avahi daemon
  mdns-reflector:
    build:
      context: ./docker/avahi
      dockerfile: Dockerfile
    container_name: esp-test-mdns
    networks:
      esp-test-network:
        ipv4_address: 172.20.0.14
    volumes:
      - ./docker/avahi/avahi-daemon.conf:/etc/avahi/avahi-daemon.conf:ro
      - ./docker/avahi/services:/etc/avahi/services:ro
    restart: unless-stopped
    privileged: true

  # SMB/CIFS File Server
  smb-server:
    image: dperson/samba:latest
    container_name: esp-test-smbserver
    ports:
      - "139:139"
      - "445:445"
    environment:
      TZ: UTC
    command: >
      -u "testuser;testpass"
      -s "public;/share;yes;no;no;all;none;testuser"
      -s "docs;/docs;yes;no;no;all;none;testuser"
    volumes:
      - ./docker/smb-data:/share:rw
      - ./docker/smb-docs:/docs:rw
    networks:
      esp-test-network:
        ipv4_address: 172.20.0.15
    restart: unless-stopped

  # Modbus TCP Server
  modbus-server:
    build:
      context: ./docker/modbus
      dockerfile: Dockerfile
    container_name: esp-test-modbusserver
    ports:
      - "502:502"
    environment:
      MODBUS_DEVICE_ID: 1
      MODBUS_PORT: 502
    volumes:
      - ./docker/modbus/config:/app/config:ro
    networks:
      esp-test-network:
        ipv4_address: 172.20.0.16
    restart: unless-stopped

  # ESP-IDF Build Environment for testing
  esp-idf:
    build:
      context: ./docker/esp-idf
      dockerfile: Dockerfile
    container_name: esp-test-build
    volumes:
      - .:/workspace:rw
      - esp-idf-cache:/opt/esp/idf
    working_dir: /workspace
    networks:
      esp-test-network:
        ipv4_address: 172.20.0.20
    environment:
      - IDF_PATH=/opt/esp/idf
    stdin_open: true
    tty: true
    command: /bin/bash

  # Test Runner - Simulates ESP32 environment
  test-runner:
    build:
      context: ./docker/test-runner
      dockerfile: Dockerfile
    container_name: esp-test-runner
    volumes:
      - .:/workspace:rw
    working_dir: /workspace
    networks:
      esp-test-network:
        ipv4_address: 172.20.0.21
    depends_on:
      - web-server
      - ftp-server
      - ssh-server
      - print-server
      - mdns-reflector
      - smb-server
      - modbus-server
    environment:
      - TEST_NETWORK=172.20.0.0/24
    stdin_open: true
    tty: true

networks:
  esp-test-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

volumes:
  esp-idf-cache:
